### PR TITLE
Fix formatting for flake8 compliance

### PR DESCRIPTION
**Pull request by lekum**
For addressing https://github.com/vinyldns/vinyldns-python/issues/14

The command for travis would just be:

```
flake8
```

If there are errors, the return code will be different than 0 and the build will fail :+1:

### CODE REVIEW

**Comment by rebstar6** [comment]
Awesome, thanks @lekum! just posted https://github.com/vinyldns/vinyldns-python/pull/16 and setup travis to just run flake08 on our vinyldns_python folder. will merge so travis is actually doing something and have it run this branch. *should* return correctly.

**Comment by rebstar6** [comment]
hmm strange. seems like there are more `line too long` errors coming up - if you have a chance and want to address those too, please do :)

**Comment by lekum** [comment]
I use to work with the Django recommended line length of 119 characters that give a bit more room for the code, instead of the default 79. On my computer I have set it up with this file:

```
$ cat ~/.flake8 
[flake8]
max-line-length = 119
```

Do you want me to make Travis check for 119 characters of line length?

**Comment by lekum** [comment]
I have added the `.flake8` file to the repo and now the `flake8` command of Travis [exits successfully](https://travis-ci.org/vinyldns/vinyldns-python/builds/443894023). The pydocstyle command fails because the PEP257 fixes are  still not merged.

**Comment by pauljamescleary** [comment]
@lekum we generally use 120 for the line length in other places as well.  I am good with that 👍

**Comment by rebstar6** [comment]
@lekum merged the pep pr, must have conflicted with this - once conflicts are resolved, this one should be good to go too

**Comment by rebstar6** [comment]
pulled into https://github.com/vinyldns/vinyldns-python/pull/25

**Pull request closed without merging**
